# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "demo-app-kazi"
client_id = "478564b157e5c62c2b02a66a48c9d3c0"
application_url = "https://texas-competition-vulnerability-symbols.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://texas-competition-vulnerability-symbols.trycloudflare.com/auth/callback",
  "https://texas-competition-vulnerability-symbols.trycloudflare.com/auth/shopify/callback",
  "https://texas-competition-vulnerability-symbols.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo-store-kazi.myshopify.com"
